sudo: false
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn install
script:
  - yarn lint
  - yarn test --coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
